<!DOCTYPE html>
<html lang="en"><head>
<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/tabby.min.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-969ddfa49e00a70eb3423444dbc81f6c.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.25">

  <meta name="author" content="Dominique MakowskiD.Makowski@sussex.ac.uk">
  <title>Bayesian Statistics</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="index_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="index_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #e1e4e8; background-color: #24292e; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #e1e4e8; } /* Normal */
    code span.al { color: #ff5555; font-weight: bold; } /* Alert */
    code span.an { color: #6a737d; } /* Annotation */
    code span.at { color: #f97583; } /* Attribute */
    code span.bn { color: #79b8ff; } /* BaseN */
    code span.bu { color: #f97583; } /* BuiltIn */
    code span.cf { color: #f97583; } /* ControlFlow */
    code span.ch { color: #9ecbff; } /* Char */
    code span.cn { color: #79b8ff; } /* Constant */
    code span.co { color: #6a737d; } /* Comment */
    code span.cv { color: #6a737d; } /* CommentVar */
    code span.do { color: #6a737d; } /* Documentation */
    code span.dt { color: #f97583; } /* DataType */
    code span.dv { color: #79b8ff; } /* DecVal */
    code span.er { color: #ff5555; text-decoration: underline; } /* Error */
    code span.ex { color: #f97583; font-weight: bold; } /* Extension */
    code span.fl { color: #79b8ff; } /* Float */
    code span.fu { color: #b392f0; } /* Function */
    code span.im { color: #9ecbff; } /* Import */
    code span.in { color: #6a737d; } /* Information */
    code span.kw { color: #f97583; } /* Keyword */
    code span.op { color: #e1e4e8; } /* Operator */
    code span.ot { color: #b392f0; } /* Other */
    code span.pp { color: #f97583; } /* Preprocessor */
    code span.re { color: #6a737d; } /* RegionMarker */
    code span.sc { color: #79b8ff; } /* SpecialChar */
    code span.ss { color: #9ecbff; } /* SpecialString */
    code span.st { color: #9ecbff; } /* String */
    code span.va { color: #ffab70; } /* Variable */
    code span.vs { color: #9ecbff; } /* VerbatimString */
    code span.wa { color: #ff5555; } /* Warning */
  </style>
  <link rel="stylesheet" href="index_files/libs/revealjs/dist/theme/quarto-61f1b1f9639486d0013a71a02afd7ce5.css">
  <link href="index_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="index_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="index_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="index_files/libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="index_files/libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="index_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-background-color="black" data-background-image="https://github.com/RealityBending/RealityBending.github.io/blob/main/assets/media/sussex.png?raw=true" data-background-opacity="0.2" class="quarto-title-block center">
  <h1 class="title">Bayesian Statistics</h1>
  <p class="subtitle"><strong>7. Posteriors</strong></p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
<sub>Dominique Makowski</sub><br><sub><sup><em>D.Makowski@sussex.ac.uk</em></sup></sub> 
</div>
</div>
</div>

</section>
<section id="installing-brms" class="slide level2">
<h2>Installing <code>brms</code></h2>
<ul>
<li class="fragment">Make sure you have successfuly made <code>brms</code> work (see last week’s instructions). If not, get in touch!</li>
</ul>
<!-- ## Bayesian vs. Frequentist -->
<!-- - Main difference is that it doesn't rely on complicated assumptions and algorithms to estimate parameters -->
<!-- - Instead, it relies on **Bayes' theorem** to compute the **posterior distribution** of the parameters of interest -->
<!-- - Frequentist estimation: Data * Model * Optimization Algorithm -> result (best fitting parameters) -> inference relies on further assumptions -->
<!-- - Bayesian estimation does not rely on assumptions, but instead, starts with initial "results" (priors), and then updates these results based on the data -->
<!-- - Every statistical parameter that we want to estimate has to start with a prior distribution -->
</section>
<section id="history-of-statistics" class="slide level2">
<h2>History of Statistics</h2>
<div class="columns" style="font-size: 90%;">
<div class="column" style="width:50%;">
<ul>
<li class="fragment"><strong>Frequentism</strong>
<ul>
<li class="fragment">1900: Karl Pearson develops the chi-squared and correlation test</li>
<li class="fragment">1913: Ronald Fisher introduces the concept of likelihood</li>
<li class="fragment">1920s: Fisher develops maximum likelihood estimation (MLE) and analysis of variance (ANOVA)</li>
<li class="fragment">1927: Jerzy Neyman and Egon Pearson (son of Karl Pearson) introduce hypothesis testing and confidence intervals</li>
<li class="fragment">1950s: Frequentism becomes the dominant statistical approach in most scientific disciplines</li>
</ul></li>
</ul>
</div><div class="column" style="width:50%;">
<ul>
<li class="fragment"><strong>Bayesianism</strong>
<ul>
<li class="fragment">1763: Thomas Bayes’ essay “An Essay towards solving a Problem in the Doctrine of Chances” published posthumously</li>
<li class="fragment">1812: Pierre-Simon Laplace, a French mathematician and physicist, extended and formalized Bayesian probability theory</li>
<li class="fragment">… Not much happening …</li>
<li class="fragment">1950s: Leonard Jimmie Savage lays the foundation for modern Bayesian statistics</li>
<li class="fragment">1960s: Work by Jeffrey explores the philosophical and practical aspects of Bayesian inference</li>
<li class="fragment">1980s: Bayesian statistics becomes increasingly applicable thanks to advancements in computing power and algorithms (MCMC)</li>
</ul></li>
</ul>
</div></div>
</section>
<section id="why-such-a-gap" class="slide level2">
<h2>Why such a gap?</h2>
<div class="columns">
<div class="column" style="width:70%;">
<ul>
<li class="fragment">We know the Bayes’ theorem since the 18th century (actually predates Frequentist statistics)</li>
<li class="fragment">But Bayesian statistics really didn’t appear until the 1960’s, with a real boom in the 2000’s</li>
<li class="fragment">Why did it take 250 years to take off?</li>
<li class="fragment">Because performing Bayesian inference for real data (not just estimating Bayes factors) is hard, and could only be achieved with the advent of modern computers</li>
</ul>
</div><div class="column" style="width:30%;">
<p><img data-src="img/Thomas_Bayes.gif"></p>
</div></div>
</section>
<section id="correlation" class="slide level2">
<h2>Correlation</h2>
<ul>
<li class="fragment">The <code>BayesFactor</code> package allows us to compute Bayes factors using a mathematical trick without performing “full” Bayesian inference</li>
</ul>
<div class="fragment">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="" aria-hidden="true" tabindex="-1"></a>result <span class="ot">&lt;-</span> BayesFactor<span class="sc">::</span><span class="fu">correlationBF</span>(mtcars<span class="sc">$</span>mpg, mtcars<span class="sc">$</span>qsec)</span>
<span id="cb1-2"><a href="" aria-hidden="true" tabindex="-1"></a>result</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Bayes factor analysis
--------------
[1] Alt., r=0.333 : 4.416463 ±0%

Against denominator:
  Null, rho = 0 
---
Bayes factor type: BFcorrelation, Jeffreys-beta*</code></pre>
</div>
</div>
</div>
<ul>
<li class="fragment"><span class="math inline">\(BF_{10} = 4.42\)</span> is moderate evidence for the existence of a correlation…
<ul>
<li class="fragment">But in what direction? Of what magnitude?</li>
</ul></li>
<li class="fragment">What if we want to describe the correlation coefficient?</li>
<li class="fragment">In a Bayesian context, this means to analyze our beliefs about the correlation coefficient after observing the data. <span class="fragment"><strong>Bayes’ Theorem</strong>: <span class="math inline">\(\underbrace{P(H|data)}_{Posterior} = \underbrace{P(H)}_{Prior}~\underbrace{P(data|H)}_{Likelihood}\)</span></span></li>
<li class="fragment">This is called the <strong>Posterior</strong>, and is the last ingredient of Bayesian inference - Priors * (model + data) = Posterior</li>
</ul>
</section>
<section id="posterior-description" class="slide level2">
<h2>Posterior Description</h2>
<ul>
<li class="fragment">The results obtained by <code>BayesFactor</code> don’t contain the posterior, because it is not computed by default (the package focuses on estimating Bayes Factors in the most efficient way possible)</li>
<li class="fragment">We can compute it using the <code>posterior()</code> function and specifying the number of iterations (i.e., the number of “draws”)</li>
</ul>
<div class="fragment">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="" aria-hidden="true" tabindex="-1"></a>posterior <span class="ot">&lt;-</span> BayesFactor<span class="sc">::</span><span class="fu">posterior</span>(result, <span class="at">iterations=</span><span class="dv">500</span>)</span>
<span id="cb3-2"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(posterior)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Markov Chain Monte Carlo (MCMC) output:
Start = 1 
End = 7 
Thinning interval = 1 
           rho      zeta
[1,] 0.4061366 0.4309760
[2,] 0.4595994 0.4968032
[3,] 0.3391690 0.3531532
[4,] 0.3391690 0.3531532
[5,] 0.5697774 0.6471931
[6,] 0.2361734 0.2407175
[7,] 0.3211367 0.3329140</code></pre>
</div>
</div>
</div>
</section>
<section id="mcmc" class="slide level2">
<h2>MCMC</h2>
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li class="fragment">It performs the sampling using a technique called <strong>Markov Chain Monte Carlo (MCMC)</strong>, which is a family of algorithms that allow to sample from a distribution without knowing its exact shape.</li>
<li class="fragment">This is because, while we can calculate the exact Bayesian posterior of simple known distributions, it becomes very hard for <strong>empirical distributions</strong> (i.e., distributions that don’t have a formula, such as that of the data).</li>
<li class="fragment">We say that the posterior is <strong>intractable</strong> (i.e., we can’t compute it analytically using formulas).</li>
</ul>
</div><div class="column">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(posterior)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Markov Chain Monte Carlo (MCMC) output:
Start = 1 
End = 7 
Thinning interval = 1 
           rho      zeta
[1,] 0.4061366 0.4309760
[2,] 0.4595994 0.4968032
[3,] 0.3391690 0.3531532
[4,] 0.3391690 0.3531532
[5,] 0.5697774 0.6471931
[6,] 0.2361734 0.2407175
[7,] 0.3211367 0.3329140</code></pre>
</div>
</div>
<ul>
<li class="fragment">While the exact posterior distribution is intractable, we can approximate it by <strong>drawing <em>n</em> random samples</strong> from it</li>
<li class="fragment">This is what MCMC does, and this is why computational power is typically needed to perform Bayesian inference</li>
</ul>
</div></div>
</section>
<section id="mcmc-1" class="slide level2 scrollable">
<h2>MCMC</h2>
<ul>
<li class="fragment">MCMC is a key milestone in the history of Bayesian statistics, because it allows us to perform Bayesian inference for complex models</li>
<li class="fragment">In general, “Bayesian sampling” is a hot area of research with lots of improvements and developments over the past &amp; next couple of years</li>
<li class="fragment">MCMC is a family of algorithms<sup>1</sup>, and the core idea is that we obtain a random sample from the (inaccessible) posterior distribution</li>
<li class="fragment">The more samples we have, the better the approximation of the posterior distribution is</li>
<li class="fragment">But sampling takes time: <strong>often a tradeoff between accuracy and speed</strong></li>
</ul>
<aside><ol class="aside-footnotes"><li id="fn1"><p>https://chi-feng.github.io/mcmc-demo/app.html?algorithm=RandomWalkMH&amp;target=banana</p></li></ol></aside></section>
<section id="quizz" class="slide level2" data-background-color="#FFAB91">
<h2>Quizz</h2>
<ul>
<li class="fragment">Doing Bayesian Statistics often involves describing the posterior distribution (the updated beliefs about some statistical parameters, e.g., the correlation value)</li>
<li class="fragment">Computing the posterior distribution is easy and can be done with formulas</li>
<li class="fragment">In real-world problems, the exact posterior distribution is <em>intractable</em> (i.e., we can’t compute it analytically using formulas)</li>
<li class="fragment">Not being able to compute the posterior analytically means that we cannot draw random samples from this distribution</li>
<li class="fragment">Drawing many samples from the posterior allows us to get an empirical approximation of the posterior distribution</li>
<li class="fragment">The process of random sampling is called <strong>York Chain Monte Altro (YMCA)</strong></li>
<li class="fragment">The process of random sampling is called <strong>Markov Chain Monte Carlo (MCMC)</strong></li>
</ul>
</section>
<section id="mcmc-chains-inspection" class="slide level2">
<h2>MCMC Chains Inspection</h2>
<div class="columns" style="font-size: 90%;">
<div class="column" style="width:50%;">
<ul>
<li class="fragment">MCMC is a process that should be inspected to ensure that it is working properly</li>
<li class="fragment">It can go wrong (e.g., not converged)</li>
</ul>
<div class="fragment">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(posterior)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Markov Chain Monte Carlo (MCMC) output:
Start = 1 
End = 7 
Thinning interval = 1 
           rho      zeta
[1,] 0.4061366 0.4309760
[2,] 0.4595994 0.4968032
[3,] 0.3391690 0.3531532
[4,] 0.3391690 0.3531532
[5,] 0.5697774 0.6471931
[6,] 0.2361734 0.2407175
[7,] 0.3211367 0.3329140</code></pre>
</div>
</div>
</div>
<ul>
<li class="fragment">In the example above, we have drawn 500 samples from the posterior distribution</li>
<li class="fragment">The returned object shows us the values of 2 variables, the correlation coefficient <code>rho</code> and <code>zeta</code> (a transformed version of the correlation coefficient that is not important)</li>
</ul>
</div><div class="column" style="width:50%;">
<div class="fragment">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(posterior)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="index_files/figure-revealjs/unnamed-chunk-6-1.png" width="3000"></p>
</figure>
</div>
</div>
</div>
</div>
<ul>
<li class="fragment">The plot on the right is the density plot of the parameter, and on the left it shows the <strong>“trace plots”</strong> of the MCMC chain</li>
<li class="fragment">Trace plots should look like “Hairy Caterpillars” 🐛, i.e., stationary (overall flat) and “random” (noisy)</li>
<li class="fragment"><strong>Put a pin in that</strong>: We will come back to “model diagnostic” in the future</li>
</ul>
</div></div>
</section>
<section id="posterior-description-1" class="slide level2">
<h2>Posterior Description</h2>
<ul>
<li class="fragment">Once we <strong>assessed our sampling process</strong> and made sure the posterior has been correctly explored and sampled from, we can proceed to <strong>visualize and describe</strong> the posterior distribution</li>
</ul>
<div class="fragment">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(posterior)</span>
<span id="cb10-2"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> data <span class="sc">|&gt;</span> </span>
<span id="cb10-4"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>rho)) <span class="sc">+</span></span>
<span id="cb10-5"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">fill=</span><span class="st">"purple"</span>) <span class="sc">+</span></span>
<span id="cb10-6"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept=</span><span class="dv">0</span>, <span class="at">linetype=</span><span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb10-7"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb10-8"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Correlation Coefficient"</span>, <span class="at">y=</span><span class="st">"Probability"</span>) <span class="sc">+</span></span>
<span id="cb10-9"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">xlim=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb10-10"><a href="" aria-hidden="true" tabindex="-1"></a>p</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="index_files/figure-revealjs/unnamed-chunk-7-1.png" width="3000"></p>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="add-prior" class="slide level2">
<h2>Add Prior</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="" aria-hidden="true" tabindex="-1"></a>rscale <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">3</span></span>
<span id="cb11-2"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="" aria-hidden="true" tabindex="-1"></a>prior <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb11-4"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> <span class="fu">dbeta</span>(<span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">length.out=</span><span class="dv">100</span>), <span class="dv">1</span><span class="sc">/</span>rscale, <span class="dv">1</span><span class="sc">/</span>rscale),</span>
<span id="cb11-5"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>, <span class="at">length.out=</span><span class="dv">100</span>)</span>
<span id="cb11-6"><a href="" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-7"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-8"><a href="" aria-hidden="true" tabindex="-1"></a>p <span class="sc">+</span> </span>
<span id="cb11-9"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_area</span>(<span class="at">data=</span>prior, <span class="fu">aes</span>(<span class="at">x=</span>x, <span class="at">y=</span>y), <span class="at">fill=</span><span class="st">"orange"</span>, <span class="at">alpha=</span>.<span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb11-10"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Beliefs about rho before (orange) and after (purple) seeing the data"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="index_files/figure-revealjs/unnamed-chunk-8-1.png" width="3000" class="r-stretch"></section>
<section id="impact-of-prior-on-posterior" class="slide level2">
<h2>Impact of Prior on Posterior</h2>
<div style="font-size: 90%;">
<ul>
<li>As we have seen, priors and models specification have a strong influence on Bayes Factors</li>
<li>But they also have an impact on the posterior distribution</li>
</ul>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="" aria-hidden="true" tabindex="-1"></a>simulate_results <span class="ot">&lt;-</span>  <span class="cf">function</span>(V1, V2) {</span>
<span id="cb12-2"><a href="" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb12-3"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Initialize dataframes</span></span>
<span id="cb12-4"><a href="" aria-hidden="true" tabindex="-1"></a>  data_priors <span class="ot">&lt;-</span> <span class="fu">data.frame</span>()</span>
<span id="cb12-5"><a href="" aria-hidden="true" tabindex="-1"></a>  data_posteriors <span class="ot">&lt;-</span> <span class="fu">data.frame</span>()</span>
<span id="cb12-6"><a href="" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb12-7"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span>(rscale <span class="cf">in</span> <span class="fu">c</span>(<span class="fl">0.05</span>, <span class="fl">0.1</span>, <span class="dv">1</span><span class="sc">/</span><span class="fu">sqrt</span>(<span class="dv">27</span>), <span class="dv">1</span><span class="sc">/</span><span class="dv">3</span>, <span class="dv">1</span><span class="sc">/</span><span class="fu">sqrt</span>(<span class="dv">3</span>), <span class="dv">1</span>)) {</span>
<span id="cb12-8"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Prior</span></span>
<span id="cb12-9"><a href="" aria-hidden="true" tabindex="-1"></a>    prior <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb12-10"><a href="" aria-hidden="true" tabindex="-1"></a>      <span class="at">y =</span> <span class="fu">dbeta</span>(<span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">length.out=</span><span class="dv">100</span>), <span class="dv">1</span><span class="sc">/</span>rscale, <span class="dv">1</span><span class="sc">/</span>rscale),</span>
<span id="cb12-11"><a href="" aria-hidden="true" tabindex="-1"></a>      <span class="at">x =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>, <span class="at">length.out=</span><span class="dv">100</span>),</span>
<span id="cb12-12"><a href="" aria-hidden="true" tabindex="-1"></a>      <span class="at">rscale =</span> insight<span class="sc">::</span><span class="fu">format_value</span>(rscale)</span>
<span id="cb12-13"><a href="" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb12-14"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="co"># prior$y &lt;- prior$y / max(prior$y)  # Normalize y (for visualization)</span></span>
<span id="cb12-15"><a href="" aria-hidden="true" tabindex="-1"></a>    data_priors <span class="ot">&lt;-</span> <span class="fu">rbind</span>(data_priors, prior)</span>
<span id="cb12-16"><a href="" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb12-17"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Compute results</span></span>
<span id="cb12-18"><a href="" aria-hidden="true" tabindex="-1"></a>    result <span class="ot">&lt;-</span> BayesFactor<span class="sc">::</span><span class="fu">correlationBF</span>(V1, V2, <span class="at">rscale=</span>rscale)</span>
<span id="cb12-19"><a href="" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb12-20"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Sample posterior</span></span>
<span id="cb12-21"><a href="" aria-hidden="true" tabindex="-1"></a>    posterior <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(BayesFactor<span class="sc">::</span><span class="fu">posterior</span>(result, <span class="at">iterations=</span><span class="dv">2000</span>))</span>
<span id="cb12-22"><a href="" aria-hidden="true" tabindex="-1"></a>    posterior<span class="sc">$</span>rscale <span class="ot">&lt;-</span> insight<span class="sc">::</span><span class="fu">format_value</span>(rscale)</span>
<span id="cb12-23"><a href="" aria-hidden="true" tabindex="-1"></a>    data_posteriors <span class="ot">&lt;-</span> <span class="fu">rbind</span>(data_posteriors, posterior)</span>
<span id="cb12-24"><a href="" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb12-25"><a href="" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb12-26"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Make plot</span></span>
<span id="cb12-27"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(data_priors, <span class="fu">aes</span>(<span class="at">color=</span>rscale)) <span class="sc">+</span></span>
<span id="cb12-28"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x=</span>x, <span class="at">y=</span>y), <span class="at">linewidth=</span><span class="dv">1</span>, <span class="at">linetype=</span><span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb12-29"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_density</span>(<span class="at">data=</span>data_posteriors, <span class="fu">aes</span>(<span class="at">x=</span>rho), <span class="at">alpha=</span>.<span class="dv">2</span>, <span class="at">linewidth=</span><span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb12-30"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb12-31"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Correlation Coefficient"</span>, <span class="at">y=</span><span class="st">"Probability"</span>) <span class="sc">+</span></span>
<span id="cb12-32"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="fu">coord_cartesian</span>(<span class="at">xlim=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb12-33"><a href="" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">simulate_results</span>(mtcars<span class="sc">$</span>mpg, mtcars<span class="sc">$</span>qsec)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="index_files/figure-revealjs/unnamed-chunk-10-1.png" width="3000"></p>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="impact-of-prior-on-posterior-1" class="slide level2">
<h2>Impact of Prior on Posterior</h2>
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li>What if we have even less data (current sample size is 32)?</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">simulate_results</span>(mtcars<span class="sc">$</span>mpg[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>], mtcars<span class="sc">$</span>qsec[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="fragment">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="index_files/figure-revealjs/unnamed-chunk-12-1.png" width="3000"></p>
</figure>
</div>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<div class="fragment">
<ul>
<li>What if we have more data?</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="" aria-hidden="true" tabindex="-1"></a>idx <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">32</span>, <span class="dv">250</span>, <span class="at">replace=</span><span class="cn">TRUE</span>)</span>
<span id="cb15-2"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">simulate_results</span>(mtcars<span class="sc">$</span>mpg[idx], mtcars<span class="sc">$</span>qsec[idx])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
<div class="fragment">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="index_files/figure-revealjs/unnamed-chunk-14-1.png" width="3000"></p>
</figure>
</div>
</div>
</div>
</div>
</div></div>
</section>
<section id="priors-and-posteriors" class="slide level2">
<h2>Priors and Posteriors</h2>
<ul>
<li class="fragment">Priors have an effect, especially when evidence from data is weak (e.g., small sample size)</li>
<li class="fragment">This is why we say that “Bayesian statistics are useful when we have little data”
<ul>
<li class="fragment">This is because we can set informative priors based on our knowledge that can help us make better inferences</li>
<li class="fragment">But if there is clear evidence from the data, the prior doesn’t matter that much <!-- - **"If the data speaks clearly, Bayes will hear it"** --></li>
</ul></li>
<li class="fragment">The more data, the higher our posterior precision (narrower posterior = lower <strong>uncertainty</strong>)</li>
<li class="fragment">This is where Bayesian statistics shine: they allow us to quantify the uncertainty associated with our estimates by describing the posterior distribution (in particular, its width)</li>
</ul>
</section>
<section id="priors-and-posteriors-1" class="slide level2">
<h2>Priors and Posteriors</h2>
<div class="columns">
<div class="column" style="font-size: 90%;">
<ul>
<li class="fragment">Bayesian inference is often intuitively conceptualized as a <strong>mixture</strong> between a prior distribution (<strong>expectations</strong>) and a “likelihood” distribution (representing the <strong>evidence</strong>, i.e., the data given a model), which result in the posterior distribution</li>
<li class="fragment">This posterior is seen as a compromise between the prior and the likelihood (i.e., the data)</li>
<li class="fragment">In neuroscience, this is often used in the context of the “Bayesian brain” hypothesis, which posits that the brain is a Bayesian inference machine that has prior expectations (e.g., about what it’s going to hear), that gets confronted to sensory evidence (the noisy data coming from the ears), and resolves this: what we consciously hear is the “posterior” distribution that combines the prior and the evidence</li>
</ul>
</div><div class="column">
<p><img data-src="img/BayesianInferenceMixture.png"></p>
<div class="fragment">
<p><img data-src="img/predictivecoding.png" style="width:100.0%"></p>
</div>
</div></div>
</section>
<section id="game-beware-of-your-intuitions-14" class="slide level2" data-background-color="#FFAB91">
<h2>Game: beware of your intuitions! (1/4)</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><img data-src="img/intuitionGame1a.png"></p>
<ul>
<li class="fragment">Normal prior, normal likelihood
<ul>
<li class="fragment"><span class="math inline">\(y \sim Normal(\mu,1)\)</span></li>
<li class="fragment"><span class="math inline">\(\mu \sim Normal(10,1)\)</span></li>
</ul></li>
<li class="fragment">Can you guess the shape of the posterior?</li>
</ul>
</div><div class="column" style="width:50%;">
<div class="fragment">
<p><img data-src="img/intuitionGame1b.png"></p>
</div>
<ul>
<li class="fragment">The classic flavor of Bayesian updating: the posterior is a compromise between the prior and likelihood</li>
</ul>
</div></div>
</section>
<section id="game-beware-of-your-intuitions-24" class="slide level2" data-background-color="#FFAB91">
<h2>Game: beware of your intuitions! (2/4)</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><img data-src="img/intuitionGame2a.png"></p>
<ul>
<li class="fragment">Student prior (df=2), normal likelihood
<ul>
<li class="fragment"><span class="math inline">\(y \sim Normal(\mu, 1)\)</span></li>
<li class="fragment"><span class="math inline">\(\mu \sim Student(2, 10, 1)\)</span></li>
</ul></li>
</ul>
</div><div class="column" style="width:50%;">
<div class="fragment">
<p><img data-src="img/intuitionGame2b.png"></p>
</div>
<ul>
<li class="fragment">Now the likelihood dominates: it’s thin tails are very skeptical of the prior, but the prior’s thick tails are not surprised by the likelihood</li>
<li class="fragment">Note: the mass in the tails can make a big difference!</li>
</ul>
</div></div>
</section>
<section id="game-beware-of-your-intuitions-34" class="slide level2" data-background-color="#FFAB91">
<h2>Game: beware of your intuitions! (3/4)</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><img data-src="img/intuitionGame3a.png"></p>
<ul>
<li class="fragment">Normal prior, Student likelihood (df=2)
<ul>
<li class="fragment"><span class="math inline">\(y \sim Student(2, \mu, 1)\)</span></li>
<li class="fragment"><span class="math inline">\(\mu \sim Normal(10, 1)\)</span></li>
</ul></li>
</ul>
</div><div class="column" style="width:50%;">
<div class="fragment">
<p><img data-src="img/intuitionGame3b.png"></p>
</div>
<ul>
<li class="fragment">Now the prior dominates, so reason as previous example but in reverse</li>
</ul>
</div></div>
</section>
<section id="game-beware-of-your-intuitions-44" class="slide level2" data-background-color="#FFAB91">
<h2>Game: beware of your intuitions! (4/4)</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><img data-src="img/intuitionGame4a.png"></p>
<ul>
<li class="fragment">Student prior, student likelihood (df=2)
<ul>
<li class="fragment"><span class="math inline">\(y \sim Student(2, \mu, 1)\)</span></li>
<li class="fragment"><span class="math inline">\(\mu \sim Student(2, 10, 1)\)</span></li>
</ul></li>
</ul>
</div><div class="column" style="width:50%;">
<div class="fragment">
<p><img data-src="img/intuitionGame4b.png"></p>
</div>
<ul>
<li class="fragment">The two modes persist: the extra mass in the tails means each distribution finds the other’s mode more plausible and so the average isn’t the best “compromise”</li>
</ul>
</div></div>
</section>
<section id="posterior-description-2" class="slide level2">
<h2>Posterior Description</h2>

<img data-src="index_files/figure-revealjs/unnamed-chunk-15-1.png" width="3000" class="r-stretch"><ul>
<li class="fragment">How can we describe and report this correlation test?</li>
<li class="fragment">We can report the posterior distribution of the correlation coefficient</li>
<li class="fragment">We could (and should) visualize it, but we also often need to report it with numbers (e.g., in a paper)</li>
<li class="fragment">Because it is “just” a distribution, we can re-use the concepts that we have seen for <strong>bootstrapping</strong></li>
<li class="fragment">We need to report various indices to convey as much information as we can about this distribution</li>
</ul>
</section>
<section id="indices-of-centrality" class="slide level2">
<h2>Indices of Centrality</h2>
<div style="font-size: 90%">
<ul>
<li class="fragment">We want to describe the “center” / “typical” value of the posterior distribution</li>
<li class="fragment">What indices to you know?</li>
<li class="fragment"><strong>Mean</strong></li>
</ul>
<div class="fragment">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the vector of rho values</span></span>
<span id="cb16-2"><a href="" aria-hidden="true" tabindex="-1"></a>rvals <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(posterior)<span class="sc">$</span>rho</span>
<span id="cb16-3"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(rvals)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3477762</code></pre>
</div>
</div>
</div>
<ul>
<li class="fragment"><strong>Median</strong></li>
</ul>
<div class="fragment">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(rvals)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3662127</code></pre>
</div>
</div>
</div>
<ul>
<li class="fragment">(Mode) <strong>MAP</strong> (Maximum A <em>Posteriori</em>)</li>
</ul>
<div class="fragment">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">as.numeric</span>(bayestestR<span class="sc">::</span><span class="fu">map_estimate</span>(rvals))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        x 
0.4022657 </code></pre>
</div>
</div>
</div>
<ul>
<li class="fragment">Which one to pick?
<ul>
<li class="fragment"><strong>Up to you!</strong> But be mindful.</li>
</ul></li>
<li class="fragment">I recommend the median because it is less jittery and has a probabilistic meaning (the effect has 50% to be lower and 50% to be higher)</li>
</ul>
</div>
</section>
<section id="point-estimates---note" class="slide level2 scrollable">
<h2>Point-estimates - Note</h2>
<ul>
<li class="fragment">The index of centrality that we reported is often referred to as a “point-estimate” of the parameter’s central tendency (e.g., “the” correlation coefficient)
<ul>
<li class="fragment"><em>Note that we can also talk about “point-estimates of dispersion” etc., point-estimate just means “single value” summary</em></li>
</ul></li>
<li class="fragment">When re-used (in other analyses, meta-analyses, …), it inevitably carries a loss of information (e.g., uncertainty).
<ul>
<li class="fragment">E.g., computing the Bayesian correlation within each participant between RT and number of errors, and then using the “point-estimate” to further relate it to personality traits<sup>1</sup></li>
</ul></li>
</ul>
<aside><ol class="aside-footnotes"><li id="fn2"><p>Unfortunately, <em>propagating uncertainty</em>, i.e., re-using estimations of uncertainty in follow-up analyses, is not common practice (and is technically challenging)</p></li></ol></aside></section>
<section id="indices-of-uncertainty---deviation" class="slide level2">
<h2>Indices of Uncertainty - Deviation</h2>
<ul>
<li class="fragment">We want to describe the “uncertainty” / “variability” of the posterior distribution</li>
<li class="fragment">This informs us about the “precision” of our estimate</li>
<li class="fragment"><strong>What index?</strong></li>
<li class="fragment"><strong>Standard deviation</strong>: the SD of the posterior is the “equivalent”** of the standard error (SE) in Frequentist models. But its interpretation is more straightforward: it is the average distance of the values from the mean. Whereas the Frequentist SE is the deviation of sample means if we drew infinite samples from the parent population (which is a bit more abstract).</li>
</ul>
<div class="fragment">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(rvals)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1487645</code></pre>
</div>
</div>
</div>
<ul>
<li class="fragment"><strong>MAD</strong>: the Median Absolute Deviation is the median of the absolute deviations from the median. It is more robust to outliers than the SD.</li>
</ul>
<div class="fragment">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">mad</span>(rvals)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1491232</code></pre>
</div>
</div>
</div>
</section>
<section id="indices-of-uncertainty---intervals-range" class="slide level2 scrollable">
<h2>Indices of Uncertainty - Intervals (Range)</h2>
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li class="fragment">One can also communicate uncertainty by reporting “credibility” (i.e., certainty) intervals</li>
<li class="fragment">What bounds? 95%? 90%? 89%?</li>
</ul>
<div class="fragment">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="" aria-hidden="true" tabindex="-1"></a>ci <span class="ot">&lt;-</span> bayestestR<span class="sc">::</span><span class="fu">eti</span>(rvals, <span class="at">ci=</span><span class="fu">c</span>(<span class="fl">0.50</span>, <span class="fl">0.89</span>, <span class="fl">0.90</span>, <span class="fl">0.95</span>))</span>
<span id="cb26-2"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ci)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="index_files/figure-revealjs/unnamed-chunk-21-1.png" width="3000"></p>
</figure>
</div>
</div>
</div>
</div>
</div><div class="column">
<ul>
<li class="fragment">95% is the most common (because it has been used in Frequentist statistics), but it is ultimately <strong>arbitrary</strong><sup>1</sup></li>
<li class="fragment">89% has been advocated by Richard McElreath as an iconoclast move to break the 95% tradition</li>
<li class="fragment">Some people report multiple intervals (especially via plots), to help conveying the shape of the distribution</li>
<li class="fragment">(I recommend 95%)</li>
</ul>
</div></div>
<aside><ol class="aside-footnotes"><li id="fn3"><p>Even though one can find reasons to prefer this</p></li></ol></aside></section>
<section id="indices-of-uncertainty---intervals-type" class="slide level2">
<h2>Indices of Uncertainty - Intervals (Type)</h2>
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li class="fragment"><strong>What type of interval?</strong></li>
<li class="fragment"><strong>Equal-tailed intervals (ETI)</strong>: Quantiles are values that split the distribution into equal parts (e.g., the 2.5% quantile is the value below which 2.5% of the distribution lies). Quantile-based intervals are commonly used to report the 95% most “central” values of the posterior distribution (i.e., the 95% quantile interval). They are called “equal-tailed” because they contain the same amount of probability mass on each side of the distribution.</li>
</ul>
<div class="fragment">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="" aria-hidden="true" tabindex="-1"></a>bayestestR<span class="sc">::</span><span class="fu">eti</span>(rvals)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>95% ETI: [0.05, 0.60]</code></pre>
</div>
</div>
</div>
</div><div class="column">
<ul>
<li class="fragment">Caveat: While easy to compute and to interpret, it is possible that values outside the ETI range are more probable than values inside (if the distribution is highly skewed)</li>
</ul>
<div class="fragment">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">rgamma</span>(<span class="dv">10000</span>, <span class="dv">1</span>, <span class="dv">1000</span>) <span class="sc">*</span> <span class="dv">10000</span></span>
<span id="cb29-2"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="" aria-hidden="true" tabindex="-1"></a>ci <span class="ot">&lt;-</span> bayestestR<span class="sc">::</span><span class="fu">eti</span>(x, <span class="at">ci=</span><span class="fl">0.50</span>)</span>
<span id="cb29-4"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ci)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="index_files/figure-revealjs/unnamed-chunk-23-1.png" width="3000"></p>
</figure>
</div>
</div>
</div>
</div>
</div></div>
</section>
<section id="indices-of-uncertainty---intervals-type-1" class="slide level2">
<h2>Indices of Uncertainty - Intervals (Type)</h2>
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li class="fragment"><strong>Highest Density Interval (HDI)</strong>: the HDI is the Bayesian equivalent of the Confidence Interval (CI). It is the interval that contains the specified probability mass (e.g., 95%) and has the highest density (i.e., is the narrowest). It is the most common interval reported in Bayesian analyses.</li>
<li class="fragment">The HDI is not straightforward to compute (is based on density estimation which is not a trivial issue)</li>
<li class="fragment">But is has the advantage of showing the most “credible” values: the values in the range are the most probable</li>
</ul>
</div><div class="column">
<div class="fragment">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="" aria-hidden="true" tabindex="-1"></a>ci <span class="ot">&lt;-</span> bayestestR<span class="sc">::</span><span class="fu">hdi</span>(x, <span class="at">ci=</span><span class="fl">0.50</span>)</span>
<span id="cb30-2"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ci)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="index_files/figure-revealjs/unnamed-chunk-24-1.png" width="3000"></p>
</figure>
</div>
</div>
</div>
</div>
<ul>
<li class="fragment">It is the most “intuitive” interval, and people often interpret Freqentist CIs as HDIs, which is not correct</li>
</ul>
</div></div>
</section>
<section id="indices-of-effect-significance" class="slide level2">
<h2>Indices of Effect “Significance”</h2>
<ul>
<li class="fragment">Indices useful to make a decision about the effect (whether it is worth mentioning and discussing or not)
<ul>
<li class="fragment">This can mean either an effect being <em>big</em> enough (“significant”)
<ul>
<li class="fragment">Relates to the concept of effect size</li>
</ul></li>
<li class="fragment">Or an effect being <em>certain</em> enough (e.g., “a positive correlation <em>exists</em> for sure, even if very very small”)</li>
</ul></li>
<li class="fragment"><strong>Bayes Factor (BF)</strong></li>
<li class="fragment"><strong>Probability of Direction</strong> (pd)</li>
<li class="fragment">Probability of being in the <strong>Region Of Practical Equivalence</strong> (ROPE)</li>
<li class="fragment">The two latter are “posterior-based indices”, as they only require the posterior distribution to be computed (although the ROPE requires the specification of a “practical equivalence” range). They are often opposed to Bayes Factors, which requires the specification of an alternative models and cannot be computed from the posterior.</li>
</ul>
</section>
<section id="probability-of-direction-pd" class="slide level2 scrollable">
<h2>Probability of Direction (pd)</h2>
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li class="fragment">The probability that the effect is positive or negative</li>
<li class="fragment">It is a Bayesian equivalent usually strongly correlated with the <em>p</em>-value</li>
</ul>
<div class="fragment">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="" aria-hidden="true" tabindex="-1"></a>rez <span class="ot">&lt;-</span> bayestestR<span class="sc">::</span><span class="fu">pd</span>(rvals)</span>
<span id="cb31-2"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(rez)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="index_files/figure-revealjs/unnamed-chunk-25-1.png" width="3000"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="" aria-hidden="true" tabindex="-1"></a>rez</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Probability of Direction

Parameter |     pd
------------------
Posterior | 98.40%</code></pre>
</div>
</div>
</div>
</div><div class="column">
<ul>
<li class="fragment">Interpretation rules of thumb<sup>1</sup>
<ul>
<li class="fragment"><strong>pd &lt;= 95%</strong> ~ <em>p</em> &gt; .1: uncertain</li>
<li class="fragment"><strong>pd &gt; 95%</strong> ~ <em>p</em> &lt; .1: possibly existing</li>
<li class="fragment"><strong>pd &gt; 97%</strong> ~ <em>p</em> &lt; .06: likely existing</li>
<li class="fragment"><strong>pd &gt; 99%</strong> ~ <em>p</em> &lt; .02: probably existing</li>
<li class="fragment"><strong>pd &gt; 99.9%</strong> ~ <em>p</em> &lt; .002: certainly existing</li>
</ul></li>
<li class="fragment">The <em>pd</em> is a good index because of its simplicity and its intuitive interpretation</li>
</ul>
</div></div>
<aside><ol class="aside-footnotes"><li id="fn4"><p>Makowski et al., (2019). <em>Indices of effect existence and significance in the Bayesian framework</em>. Frontiers in psychology, 10, 2767.</p></li></ol></aside></section>
<section id="rope-region-of-practical-equivalence" class="slide level2">
<h2>ROPE (Region Of Practical Equivalence)</h2>
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li class="fragment">The ROPE is a range of values that are considered as “practically equivalent” to zero (or to any other value)</li>
<li class="fragment">It is used to make a decision about the effect being “big” enough (i.e., “significant”)</li>
</ul>
<div class="fragment">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="" aria-hidden="true" tabindex="-1"></a>rez <span class="ot">&lt;-</span> bayestestR<span class="sc">::</span><span class="fu">rope</span>(rvals, <span class="at">rope=</span><span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.1</span>, <span class="fl">0.1</span>))</span>
<span id="cb34-2"><a href="" aria-hidden="true" tabindex="-1"></a>rez</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># Proportion of samples inside the ROPE [-0.10, 0.10]:

Inside ROPE
-----------
3.59 %     </code></pre>
</div>
</div>
</div>
<ul>
<li class="fragment">Often we use <span class="math inline">\(P_{~in~rope}&lt; .05\)</span> (= <span class="math inline">\(5\%\)</span>) as a threshold</li>
</ul>
</div><div class="column">
<div class="fragment">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(rez)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="index_files/figure-revealjs/unnamed-chunk-27-1.png" width="3000"></p>
</figure>
</div>
</div>
</div>
</div>
<ul>
<li class="fragment">Be careful, by default we consider some % of CI that is in the ROPE, so your p-ROPE highly depends on the CI bounds you choose</li>
</ul>
<div class="fragment">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="" aria-hidden="true" tabindex="-1"></a>bayestestR<span class="sc">::</span><span class="fu">rope</span>(rvals, <span class="at">rope=</span><span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.1</span>, <span class="fl">0.1</span>), <span class="at">ci=</span><span class="fl">0.90</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># Proportion of samples inside the ROPE [-0.10, 0.10]:

Inside ROPE
-----------
1.98 %     </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="" aria-hidden="true" tabindex="-1"></a>bayestestR<span class="sc">::</span><span class="fu">rope</span>(rvals, <span class="at">rope=</span><span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.1</span>, <span class="fl">0.1</span>), <span class="at">ci=</span><span class="fl">0.89</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># Proportion of samples inside the ROPE [-0.10, 0.10]:

Inside ROPE
-----------
0.45 %     </code></pre>
</div>
</div>
</div>
</div></div>
</section>
<section id="decision-fatigue" class="slide level2">
<h2>Decision Fatigue</h2>
<ul>
<li class="fragment"><em>“I hate Bayesian stats because there is so many things to decide / pay attention to”</em></li>
<li class="fragment">There is even more things we <strong><em>should</em></strong> care about in Frequentist estimation</li>
<li class="fragment">The things we care about in Bayesian statistics are much more transparently accessible and interpretable (e.g., priors, MCMC diagnostics, posterior description, …)</li>
<li class="fragment">Because applied Bayesian stats are a new field, there is not yet a very strong “standard” way to do things</li>
<li class="fragment">It is a moving and rapidly evolving field</li>
<li class="fragment">For now, best way to deal with this is to 1) understand the main concepts and indices, 2) be transparent about the choices you make</li>
<li class="fragment">Rest assured: if a result is really there, details of the approach shouldn’t matter as much, the effect should show regardless of small variations in the analysis</li>
</ul>
</section>
<section id="reporting-a-bayesian-correlation" class="slide level2">
<h2>Reporting a Bayesian Correlation</h2>
<div class="columns">
<div class="column" style="width:50%;">
<ul class="task-list">
<li class="fragment"><label><input type="checkbox" checked="">A scatter plot (regardless of Bayesian or not)</label></li>
</ul>
<div class="fragment">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="" aria-hidden="true" tabindex="-1"></a>mtcars <span class="sc">|&gt;</span> </span>
<span id="cb41-2"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>mpg, <span class="at">y=</span>qsec)) <span class="sc">+</span></span>
<span id="cb41-3"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb41-4"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">"lm"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="index_files/figure-revealjs/unnamed-chunk-29-1.png" width="3000"></p>
</figure>
</div>
</div>
</div>
</div>
<ul class="task-list">
<li class="fragment"><label><input type="checkbox" checked="">A mention of the priors</label>
<ul>
<li class="fragment">“a shifted, scaled <span class="math inline">\(Beta(3, 3)\)</span> prior distribution was used for the correlation coefficient”</li>
<li class="fragment">“Default priors from the BayesFactor package (Morey &amp; Rouder, 2023) <em>correlationBF()</em> function were used (with the <em>rscale</em> parameter being set to medium)”</li>
</ul></li>
</ul>
</div><div class="column">
<div class="fragment">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(BayesFactor)</span>
<span id="cb42-2"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-3"><a href="" aria-hidden="true" tabindex="-1"></a>report<span class="sc">::</span><span class="fu">cite_packages</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
<div class="fragment" style="font-size: 35%">
<ul>
<li>Bates D, Maechler M, Jagan M (2025). <em>Matrix: Sparse and Dense Matrix Classes and Methods</em>. R package version 1.7-2, <a href="https://CRAN.R-project.org/package=Matrix" class="uri">https://CRAN.R-project.org/package=Matrix</a>.</li>
<li>Ben-Shachar MS, Lüdecke D, Makowski D (2020). “effectsize: Estimation of Effect Size Indices and Standardized Parameters.” <em>Journal of Open Source Software</em>, <em>5</em>(56), 2815. doi:10.21105/joss.02815 <a href="https://doi.org/10.21105/joss.02815" class="uri">https://doi.org/10.21105/joss.02815</a>, <a href="https://doi.org/10.21105/joss.02815" class="uri">https://doi.org/10.21105/joss.02815</a>.</li>
<li>Grolemund G, Wickham H (2011). “Dates and Times Made Easy with lubridate.” <em>Journal of Statistical Software</em>, <em>40</em>(3), 1-25. <a href="https://www.jstatsoft.org/v40/i03/" class="uri">https://www.jstatsoft.org/v40/i03/</a>.</li>
<li>Lüdecke D, Ben-Shachar M, Patil I, Makowski D (2020). “Extracting, Computing and Exploring the Parameters of Statistical Models using R.” <em>Journal of Open Source Software</em>, <em>5</em>(53), 2445. doi:10.21105/joss.02445 <a href="https://doi.org/10.21105/joss.02445" class="uri">https://doi.org/10.21105/joss.02445</a>.</li>
<li>Lüdecke D, Ben-Shachar M, Patil I, Waggoner P, Makowski D (2021). “performance: An R Package for Assessment, Comparison and Testing of Statistical Models.” <em>Journal of Open Source Software</em>, <em>6</em>(60), 3139. doi:10.21105/joss.03139 <a href="https://doi.org/10.21105/joss.03139" class="uri">https://doi.org/10.21105/joss.03139</a>.</li>
<li>Lüdecke D, Ben-Shachar M, Patil I, Wiernik B, Bacher E, Thériault R, Makowski D (2022). “easystats: Framework for Easy Statistical Modeling, Visualization, and Reporting.” <em>CRAN</em>. doi:10.32614/CRAN.package.easystats <a href="https://doi.org/10.32614/CRAN.package.easystats" class="uri">https://doi.org/10.32614/CRAN.package.easystats</a>, R package, <a href="https://easystats.github.io/easystats/" class="uri">https://easystats.github.io/easystats/</a>.</li>
<li>Lüdecke D, Patil I, Ben-Shachar M, Wiernik B, Waggoner P, Makowski D (2021). “see: An R Package for Visualizing Statistical Models.” <em>Journal of Open Source Software</em>, <em>6</em>(64), 3393. doi:10.21105/joss.03393 <a href="https://doi.org/10.21105/joss.03393" class="uri">https://doi.org/10.21105/joss.03393</a>.</li>
<li>Lüdecke D, Waggoner P, Makowski D (2019). “insight: A Unified Interface to Access Information from Model Objects in R.” <em>Journal of Open Source Software</em>, <em>4</em>(38), 1412. doi:10.21105/joss.01412 <a href="https://doi.org/10.21105/joss.01412" class="uri">https://doi.org/10.21105/joss.01412</a>.</li>
<li>Makowski D, Ben-Shachar M, Lüdecke D (2019). “bayestestR: Describing Effects and their Uncertainty, Existence and Significance within the Bayesian Framework.” <em>Journal of Open Source Software</em>, <em>4</em>(40), 1541. doi:10.21105/joss.01541 <a href="https://doi.org/10.21105/joss.01541" class="uri">https://doi.org/10.21105/joss.01541</a>, <a href="https://joss.theoj.org/papers/10.21105/joss.01541" class="uri">https://joss.theoj.org/papers/10.21105/joss.01541</a>.</li>
<li>Makowski D, Ben-Shachar M, Wiernik B, Patil I, Thériault R, Lüdecke D (2025). “modelbased: An R package to make the most out of your statistical models through marginal means, marginal effects, and model predictions.” <em>Journal of Open Source Software</em>, <em>10</em>(109), 7969. doi:10.21105/joss.07969 <a href="https://doi.org/10.21105/joss.07969" class="uri">https://doi.org/10.21105/joss.07969</a>, <a href="https://joss.theoj.org/papers/10.21105/joss.07969" class="uri">https://joss.theoj.org/papers/10.21105/joss.07969</a>.</li>
<li>Makowski D, Lüdecke D, Patil I, Thériault R, Ben-Shachar M, Wiernik B (2023). “Automated Results Reporting as a Practical Tool to Improve Reproducibility and Methodological Best Practices Adoption.” <em>CRAN</em>. doi:10.32614/CRAN.package.report <a href="https://doi.org/10.32614/CRAN.package.report" class="uri">https://doi.org/10.32614/CRAN.package.report</a>, <a href="https://easystats.github.io/report/" class="uri">https://easystats.github.io/report/</a>.</li>
<li>Makowski D, Wiernik B, Patil I, Lüdecke D, Ben-Shachar M (2022). “correlation: Methods for Correlation Analysis.” Version 0.8.3, <a href="https://CRAN.R-project.org/package=correlation" class="uri">https://CRAN.R-project.org/package=correlation</a>. Makowski D, Ben-Shachar M, Patil I, Lüdecke D (2020). “Methods and Algorithms for Correlation Analysis in R.” <em>Journal of Open Source Software</em>, <em>5</em>(51), 2306. doi:10.21105/joss.02306 <a href="https://doi.org/10.21105/joss.02306" class="uri">https://doi.org/10.21105/joss.02306</a>, <a href="https://joss.theoj.org/papers/10.21105/joss.02306" class="uri">https://joss.theoj.org/papers/10.21105/joss.02306</a>.</li>
<li>Morey R, Rouder J (2024). <em>BayesFactor: Computation of Bayes Factors for Common Designs</em>. R package version 0.9.12-4.7, <a href="https://CRAN.R-project.org/package=BayesFactor" class="uri">https://CRAN.R-project.org/package=BayesFactor</a>.</li>
<li>Müller K, Wickham H (2025). <em>tibble: Simple Data Frames</em>. R package version 3.3.0, <a href="https://CRAN.R-project.org/package=tibble" class="uri">https://CRAN.R-project.org/package=tibble</a>.</li>
<li>Patil I, Makowski D, Ben-Shachar M, Wiernik B, Bacher E, Lüdecke D (2022). “datawizard: An R Package for Easy Data Preparation and Statistical Transformations.” <em>Journal of Open Source Software</em>, <em>7</em>(78), 4684. doi:10.21105/joss.04684 <a href="https://doi.org/10.21105/joss.04684" class="uri">https://doi.org/10.21105/joss.04684</a>.</li>
<li>Pedersen T (2025). <em>patchwork: The Composer of Plots</em>. R package version 1.3.2, <a href="https://CRAN.R-project.org/package=patchwork" class="uri">https://CRAN.R-project.org/package=patchwork</a>.</li>
<li>Plummer M, Best N, Cowles K, Vines K (2006). “CODA: Convergence Diagnosis and Output Analysis for MCMC.” <em>R News</em>, <em>6</em>(1), 7-11. <a href="https://journal.r-project.org/archive/" class="uri">https://journal.r-project.org/archive/</a>.</li>
<li>R Core Team (2025). <em>R: A Language and Environment for Statistical Computing</em>. R Foundation for Statistical Computing, Vienna, Austria. <a href="https://www.R-project.org/" class="uri">https://www.R-project.org/</a>.</li>
<li>Wickham H (2016). <em>ggplot2: Elegant Graphics for Data Analysis</em>. Springer-Verlag New York. ISBN 978-3-319-24277-4, <a href="https://ggplot2.tidyverse.org" class="uri">https://ggplot2.tidyverse.org</a>.</li>
<li>Wickham H (2023). <em>forcats: Tools for Working with Categorical Variables (Factors)</em>. R package version 1.0.0, <a href="https://CRAN.R-project.org/package=forcats" class="uri">https://CRAN.R-project.org/package=forcats</a>.</li>
<li>Wickham H (2025). <em>stringr: Simple, Consistent Wrappers for Common String Operations</em>. R package version 1.5.2, <a href="https://CRAN.R-project.org/package=stringr" class="uri">https://CRAN.R-project.org/package=stringr</a>.</li>
<li>Wickham H, Averick M, Bryan J, Chang W, McGowan LD, François R, Grolemund G, Hayes A, Henry L, Hester J, Kuhn M, Pedersen TL, Miller E, Bache SM, Müller K, Ooms J, Robinson D, Seidel DP, Spinu V, Takahashi K, Vaughan D, Wilke C, Woo K, Yutani H (2019). “Welcome to the tidyverse.” <em>Journal of Open Source Software</em>, <em>4</em>(43), 1686. doi:10.21105/joss.01686 <a href="https://doi.org/10.21105/joss.01686" class="uri">https://doi.org/10.21105/joss.01686</a>.</li>
<li>Wickham H, François R, Henry L, Müller K, Vaughan D (2023). <em>dplyr: A Grammar of Data Manipulation</em>. R package version 1.1.4, <a href="https://CRAN.R-project.org/package=dplyr" class="uri">https://CRAN.R-project.org/package=dplyr</a>.</li>
<li>Wickham H, Henry L (2025). <em>purrr: Functional Programming Tools</em>. R package version 1.1.0, <a href="https://CRAN.R-project.org/package=purrr" class="uri">https://CRAN.R-project.org/package=purrr</a>.</li>
<li>Wickham H, Hester J, Bryan J (2024). <em>readr: Read Rectangular Text Data</em>. R package version 2.1.5, <a href="https://CRAN.R-project.org/package=readr" class="uri">https://CRAN.R-project.org/package=readr</a>.</li>
<li>Wickham H, Vaughan D, Girlich M (2024). <em>tidyr: Tidy Messy Data</em>. R package version 1.3.1, <a href="https://CRAN.R-project.org/package=tidyr" class="uri">https://CRAN.R-project.org/package=tidyr</a>.</li>
</ul>
</div>
</div></div>
</section>
<section id="sampling-information" class="slide level2">
<h2>Sampling Information</h2>
<div class="columns">
<div class="column" style="width:50%;">
<ul class="task-list">
<li class="fragment"><label><input type="checkbox" checked="">Mention what algorithm and how many samples</label>
<ul>
<li class="fragment"><em>“We drew 500 samples using MCMC”</em></li>
<li class="fragment"><em>“The sampling algorithm (MCMC; 500 iterations) converged.”</em></li>
</ul></li>
<li class="fragment"><label><input type="checkbox" checked="">Trace plots are mostly for you to assess convergence, but should not necessarily be reported</label></li>
</ul>
<div class="fragment">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(posterior)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="index_files/figure-revealjs/unnamed-chunk-32-1.png" width="3000"></p>
</figure>
</div>
</div>
</div>
</div>
</div><div class="column">
<ul>
<li class="fragment">Make trace plot with <code>ggplot</code>
<ul>
<li class="fragment">Plot the iterations “in order” of their sampling (from 1 to <em>i</em>)</li>
<li class="fragment">It should look like a hairy caterpillar 🐛</li>
</ul></li>
</ul>
<div class="fragment">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">r=</span>rvals, <span class="at">i=</span><span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(rvals)) <span class="sc">|&gt;</span> </span>
<span id="cb44-2"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>i, <span class="at">y=</span>r)) <span class="sc">+</span></span>
<span id="cb44-3"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb44-4"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Trace Plot of the Posterior Distribution"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="index_files/figure-revealjs/unnamed-chunk-33-1.png" width="3000"></p>
</figure>
</div>
</div>
</div>
</div>
</div></div>
</section>
<section id="posterior-distribution" class="slide level2">
<h2>Posterior Distribution</h2>
<ul class="task-list">
<li class="fragment"><label><input type="checkbox" checked="">If possible, show the posterior distribution</label></li>
</ul>
<div class="fragment">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">r=</span>rvals) <span class="sc">|&gt;</span> </span>
<span id="cb45-2"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>r)) <span class="sc">+</span></span>
<span id="cb45-3"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">fill=</span><span class="st">"orange"</span>) <span class="sc">+</span></span>
<span id="cb45-4"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Correlation Posterior Distribution"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="index_files/figure-revealjs/unnamed-chunk-34-1.png" width="3000"></p>
</figure>
</div>
</div>
</div>
</div>
<div class="fragment">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">hdi</span>(rvals))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="index_files/figure-revealjs/unnamed-chunk-35-1.png" width="3000"></p>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="centrality-and-direction" class="slide level2">
<h2>Centrality and Direction</h2>
<ul class="task-list">
<li class="fragment"><label><input type="checkbox" checked="">Index of centrality</label>
<ul>
<li class="fragment">Mean, median, MAP</li>
<li class="fragment"><em>“The median of the correlation coefficient’s posterior distribution is 0.37”</em></li>
<li class="fragment"><em>“We will report the median of the posterior distributions”</em> + <em>“The correlation was positive and significant (r = 0.37, …)”</em></li>
</ul></li>
<li class="fragment"><label><input type="checkbox" checked="">Report correlation direction</label>
<ul>
<li class="fragment">Of the centrality point-estimate</li>
<li class="fragment">“<em>The median of the correlation coefficient’s posterior distribution is positive (r = 0.37)</em></li>
<li class="fragment">Using the <em>Probability of Direction</em> (<strong>pd</strong>) index</li>
<li class="fragment">“<em>The probability of the correlation coefficient being positive (pd) is 98.40%</em>”</li>
</ul></li>
</ul>
</section>
<section id="precision" class="slide level2">
<h2>Precision</h2>
<ul class="task-list">
<li class="fragment"><label><input type="checkbox" checked="">Index of dispersion</label>
<ul>
<li class="fragment">SD, MAD</li>
<li class="fragment"><em>“(MAD = 0.15)”</em></li>
</ul></li>
<li class="fragment"><label><input type="checkbox" checked="">Credible Interval</label>
<ul>
<li class="fragment">HDI, ETI</li>
<li class="fragment"><em>“95% HDI = […, …]”</em></li>
<li class="fragment"><em>“Credible intervals were computed as Highest Density Intervals (HDI)”</em> + <em>“95% CI = […, …]”</em></li>
</ul></li>
</ul>
</section>
<section id="effect-significance" class="slide level2">
<h2>Effect significance</h2>
<ul class="task-list">
<li class="fragment"><label><input type="checkbox" checked="">Probability of direction (pd)</label>
<ul>
<li class="fragment"><em>“There is a significant probability that the correlation is positive (pd &gt; 99%)”</em></li>
</ul></li>
<li class="fragment"><label><input type="checkbox" checked="">ROPE</label>
<ul>
<li class="fragment"><em>“The ROPE was set as [-0.10, 0.10] following Cohen’s (1988) effect size recommendations for correlations and we computed the portion of the 95% CI lying inside as an index of effect significance”</em> + <em>“(p-ROPE=…)”</em></li>
<li class="fragment"><em>“The proportion of the posterior falling in the region of practical null equivalence (ROPE = [-0.10, 0.10]) is …”</em></li>
</ul></li>
<li class="fragment"><label><input type="checkbox" checked="">Bayes Factor</label>
<ul>
<li class="fragment"><em>“There is strong evidence against the null hypothesis that the correlation is null (BF10 = …)”</em></li>
</ul></li>
</ul>
</section>
<section id="effect-size" class="slide level2">
<h2>Effect size</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="" aria-hidden="true" tabindex="-1"></a>effectsize<span class="sc">::</span><span class="fu">interpret_r</span>(<span class="fu">median</span>(rvals), <span class="at">rules=</span><span class="st">"cohen1988"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "moderate"
(Rules: cohen1988)</code></pre>
</div>
</div>
<ul class="task-list">
<li class="fragment"><label><input type="checkbox" checked="">Effect size interpretation</label>
<ul>
<li class="fragment">Mention rules: <em>“We labelled the correlation effect sizes using Cohen’s (1988) rules of thumb set”</em></li>
<li class="fragment">Of the point-estimate</li>
<li class="fragment">“<em>The median of the correlation coefficient’s posterior distribution is positive and moderate”</em></li>
</ul></li>
</ul>
</div><div class="column">
<ul>
<li class="fragment">Of the posterior distribution</li>
</ul>
<div class="fragment">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="" aria-hidden="true" tabindex="-1"></a>effsizes_alldraws <span class="ot">&lt;-</span> effectsize<span class="sc">::</span><span class="fu">interpret_r</span>(rvals, <span class="at">rules=</span><span class="st">"cohen1988"</span>) </span>
<span id="cb49-2"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(effsizes_alldraws)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "moderate" "moderate" "moderate" "moderate" "large"    "small"   </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(effsizes_alldraws)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 500</code></pre>
</div>
</div>
</div>
<div class="fragment">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(effsizes_alldraws) <span class="sc">/</span> <span class="fu">length</span>(effsizes_alldraws)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>effsizes_alldraws
     large   moderate      small very small 
     0.136      0.518      0.292      0.054 </code></pre>
</div>
</div>
</div>
<ul>
<li class="fragment"><em>“The correlation has a 13.6% probability of being large, 51.8% of being moderate, 29.2% of being small and 5.40% of being very small”</em>
<ul>
<li class="fragment">Can become verbose (especially if many correlations to report): <strong>find good balance between detail and conciseness</strong></li>
</ul></li>
</ul>
</div></div>
</section>
<section id="minimal-template-sentence" class="slide level2">
<h2>Minimal Template Sentence</h2>
<ul>
<li class="fragment">“The Bayesian Pearson correlation between X and Y was estimated to be r = <em>median</em> (95% CI […, …]), with a probability of <strong><em>pd</em></strong> of being negative and can be considered as significant (<span class="math inline">\(p_{-rope}\)</span>=…)”</li>
<li class="fragment">“There was moderate evidence (<span class="math inline">\(BF_{10}=~...\)</span>) in favour of a non-null correlation between X and Y that has a probability of <strong><em>pd</em></strong> of being negative (Median = median, 89% CI […, …]) and can be considered as significant and moderate (<span class="math inline">\(p_{-rope}\)</span>=…)”</li>
</ul>
<!-- ## Spearman Correlation -->
<!-- - What are the benefits of Spearman correlations? -->
<!--   - More "robust" to outliers -->
<!-- ::: {.fragment} -->
<!-- ```{r} -->
<!-- #| echo: true -->
<!-- y <- c(0.53, 0.67, 0.70, 0.86, 0.92, 0.94, 0) -->
<!-- x <- c(100, 101, 102, 103, 104, 105, 115) -->
<!-- ggplot(data.frame(x=x, y=y), aes(x=x, y=y)) + -->
<!--   geom_point() + -->
<!--   geom_smooth(method="lm", se=FALSE) -->
<!-- cor.test(x, y, method="pearson") -->
<!-- ``` -->
<!-- ::: -->
<!-- ## Rank-Transformations -->
<!-- - Why is it more robust? What are Spearman correlations? -->
<!-- - Spearman Correlation are Pearson correlation on **"rank-transformed"** data -->
<!-- ::: {.fragment} -->
<!-- ```{r} -->
<!-- #| echo: true -->
<!-- xrank <- datawizard::ranktransform(x) -->
<!-- xrank -->
<!-- yrank <- datawizard::ranktransform(y) -->
<!-- ggplot(data.frame(x=xrank, y=yrank), aes(x=x, y=y)) + -->
<!--   geom_point() + -->
<!--   geom_smooth(method="lm", se=FALSE) -->
<!-- cor.test(x, y, method="spearman") -->
<!-- ``` -->
<!-- ::: -->
<!-- ## Spearman Bayesian Correlations -->
<!-- ::: {.fragment} -->
<!-- ```{r} -->
<!-- #| echo: true -->
<!-- cor.test(x, y, method="spearman") -->
<!-- ``` -->
<!-- ::: -->
<!-- ::: {.fragment} -->
<!-- ```{r} -->
<!-- #| echo: true -->
<!-- cor.test(xrank, yrank, method="pearson") -->
<!-- ``` -->
<!-- ::: -->
<!-- 1. Rank-transform variables -->
<!-- 2. Compute Bayesian Pearson correlation -->
<!-- ## Exercice {background-color="#FFAB91"} -->
<!-- ::: {.nonincremental} -->
<!-- - In the `iris` in-built dataset, report the Spearman correlation between `Petal.Length` and `Petal.Width` for the `setosa` species only -->
<!-- - Desired output^[Note that your exact values might slightly differ due to the *stochastic* (i.e., random) nature of the MCMC algorithm]: -->
<!-- ```{r} -->
<!-- #| echo: false -->
<!-- data <- dplyr::filter(iris, Species=="setosa") -->
<!-- rez <- BayesFactor::correlationBF(data$Petal.Length, data$Petal.Width) -->
<!-- bayestestR::describe_posterior(rez) -->
<!-- ``` -->
<!-- ::: -->
</section>
<section id="the-end-for-now" class="slide level2 center" data-background-color="#212121">
<h2>The End <sub><sup>(for now)</sup></sub></h2>
<p><em>Thank you!</em></p>

</section>

    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/University_of_Sussex_Logo.svg/480px-University_of_Sussex_Logo.svg.png" class="slide-logo"></p>
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="index_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="index_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="index_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="index_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="index_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="index_files/libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="index_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="index_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="index_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="index_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="index_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>